//============================================================================
// Name        : MailSystem.cpp
// Author      : meteor
// Version     :
// Copyright   : Your copyright notice
// Description : Hello World in C++, Ansi-style
//============================================================================
// Xcode for Qt project.
// Generated by create_qt_xcode_project.sh, Laohyx.

//#include "CMail.h"
#include "smtp.h"
#include "pop3.h"
#include <iostream>
#include <QApplication>
#include <QLabel>
#include "mainwindow.h"
#include "mainwindow_2.h"
//#include "../qt_lib/QtWidgets.framework/Versions/5/Headers/QApplication"
//#include "../qt_lib/QtWidgets.framework/Versions/5/Headers/QLabel"
using namespace std;
//
//class A{
//private:
//    int i;
//public:
//    A(int ii=0):i(ii){};
//    virtual void print()const;
//    virtual ~A(){};
//};
//
//class B:public A{
//    char *p;
//public:
//    B(int i, char *p):A(i)
//    {
//        this->p = new char[strlen(p)+1];
//        strcpy(this->p, p);
//    }
//    virtual void print() const;
//    ~B()
//    {
//        delete p;
//    }
//};

void smtpConnect(bool IsDebug)
{
    smtp smtpTest("smtp.163.com", "qqq1051814353@163.com", "qqq1051814353");
    if ( smtpTest.LoginSmtp(IsDebug) )
        smtpTest.SendMail("Meteor", "1051814353@qq.com", "Hello meteor", "My name is Meteor.", IsDebug);
}

int main(int argc, char *argv[])
{
//    long n;
//    bool IsDebug = true;
//    pop3 pop3Test("pop3.163.com", "qqq1051814353@163.com", "qqq1051814353");
//    if ( pop3Test.LoginPop3(IsDebug) )
//        pop3Test.ReceiveMail(IsDebug, n);
    
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    MainWindow_2 w_2;
    QObject::connect(&w,SIGNAL(loginSuccessful()),&w_2,SLOT(init()));
    QObject::connect(&w,SIGNAL(loginSuccessful()),&w,SLOT(close()));
    return a.exec();
    
//    int choice;
//    scanf("%d", &choice);
//    switch (choice) {
//        case 1:
//            smtpConnect(IsDebug);
//            break;
//        case 2:
//            pop3Connect(IsDebug);
//            break;
//        default:
//            break;
//    }
    
//    CMail TestMail("smtp.163.com", "pop3.163.com", "q1051814353@163.com", "q1051814353");//smtp服务器，账号，密码/授权码
//    if ( TestMail.LoginMail(IsDebug) ) {
//    	//发件人昵称，收件人邮箱地址，邮件标题，邮件内容
//    	//TestMail.SendMail("Meteor", "1051814353@qq.com", "Hello meteor", "My name is Meteor", IsDebug);
//    	TestMail.ReceiveMail(IsDebug);
//    }
//    else {
//    	std::cout << "login failed";
//    }
}

