//============================================================================
// Name        : MailSystem.cpp
// Author      : meteor
// Version     :
// Copyright   : Your copyright notice
// Description : Hello World in C++, Ansi-style
//============================================================================
// Xcode for Qt project.
// Generated by create_qt_xcode_project.sh, Laohyx.

//#include "CMail.h"
#include "smtp.h"
#include "pop3.h"
#include <iostream>
#include <QApplication>
#include <QLabel>
#include "mainwindow.h"
#include "mainwindow_2.h"
#include "mainwindow_3.h"
//#include "../qt_lib/QtWidgets.framework/Versions/5/Headers/QApplication"
//#include "../qt_lib/QtWidgets.framework/Versions/5/Headers/QLabel"
using namespace std;

int main(int argc, char *argv[])
{
//    size_t n;
//    bool IsDebug = true;
//    pop3 pop3Test("qqq1051814353@163.com", "qqq1051814353");
//    if ( pop3Test.bfLoginPop3(IsDebug) )
//        pop3Test.pmailReceiveMail(IsDebug, n);
    QApplication a(argc, argv);
    bool bIsDebug = false;
    MainWindow wLoginWindow(bIsDebug);
    wLoginWindow.show();
    MainWindow_2 wMainWindow(bIsDebug);
    MainWindow_3 wSendMailWindow(bIsDebug);
    QObject::connect(&wLoginWindow, SIGNAL(loginSuccessful(std::string, std::string)),
                     &wMainWindow, SLOT(init(std::string, std::string)));
    QObject::connect(&wLoginWindow, SIGNAL(loginSuccessful(std::string, std::string)),
                     &wLoginWindow, SLOT(close()));
    QObject::connect(&wMainWindow, SIGNAL(sWriteMail(std::string, std::string)),
                     &wSendMailWindow, SLOT(init(std::string, std::string)));
    return a.exec();
}

